services:
  - type: static
    name: carehire-client
    rootDir: client
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
